##IN THIS PROGRAM THE FOLLOWING CRITERIA MUST BE MET
#NEW CUSTOMER FORM
  #STUDENT NAME "student"
  #STUDENT BIRTHDAY 
  #STUDNET AGE 
  #NAME OF PARENT 
  #CONTACT PHONE NUMBER ABILITY TO ADD LESSONS CHECK IF THEY HAVE PAID
#NUMBER OF LESSONS
#ABILITY TO SUBTRACT LESSONS FROM THE REMAINING
#NOTES ABOUT THE LESSONS

####################READY SET GO!#####################

